CREATE TABLE employee(
emp_id INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT,
firstname VARCHAR(255)NOT NULL,
lastname VARCHAR(255)NOT NULL,
email VARCHAR(255)NOT NULL
phone VARCHAR(15)NOT NULL,
salary BIGINT(10)NOT NULL
);